use_frameworks!

platform :ios, '10.0'

target 'NahimFourthPodLib_Example' do
  pod 'NahimFourthPodLib', :path => '../'

  target 'NahimFourthPodLib_Tests' do
    inherit! :search_paths

    
  end
end
